import { describe, it, expect } from "vitest";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { defaultEngineConfig } from "../config";
import { aggregateRealism, type AggResult } from "./harness";
// 벤치 밴드는 bench.ts 가 단일 출처 — 리포트와 밸런스 스윕 도구가 같은 표를 본다(드리프트 방지).
import { BENCH, benchVerdict, type Bench } from "./bench";

/**
 * E3 리얼리즘 갭 리포트 생성기(env 가드). npm test 에서는 skip.
 * 실행: HMB_GEN_GAP=1 npx vitest run packages/engine/src/realism/gap-report.test.ts
 * → research/engine-realism-gap.md 의 데이터 표를 갱신하고 콘솔에 요약 출력.
 */

function fmt(v: number): string {
  return (Math.round(v * 100) / 100).toString();
}

function reportBody(agg: AggResult): string {
  const L: string[] = [];
  L.push(`| 지표 | 엔진(팀·경기) | ±SD | 벤치마크 | 판정 |`);
  L.push(`|---|---|---|---|---|`);
  for (const b of BENCH) {
    let v: number, s: number;
    if (b.key === "goalsPerMatch") {
      v = agg.goalsPerMatch;
      s = 0;
    } else {
      v = agg.mean[b.key];
      s = agg.sd[b.key];
    }
    const u = b.unit ?? "";
    L.push(
      `| ${b.label} | ${fmt(v)}${u} | ${fmt(s)} | ${b.lo}–${b.hi}${u}${b.note ? ` (${b.note})` : ""} | ${benchVerdict(v, b)} |`,
    );
  }
  L.push("");
  L.push(`- 골(양팀/경기): **${fmt(agg.goalsPerMatch)}** (벤치 ~2.7–3.3)`);
  L.push(`- 패스 길이 분포(팀·경기 평균): short<15m **${fmt(agg.mean.shortPassPct)}%** · medium 15–30m **${fmt(agg.mean.mediumPassPct)}%** · long>=30m **${fmt(agg.mean.longPassPct)}%**`);
  L.push(`- 시드 ${agg.seeds}개 · 팀-경기 ${agg.teamMatches} · lastHash \`${agg.lastHash}\``);
  return L.join("\n");
}

const GEN = (process as unknown as { env?: Record<string, string | undefined> }).env?.HMB_GEN_GAP;

describe("E3 realism gap report", () => {
  it.skipIf(!GEN)("aggregates real config vs benchmark", () => {
    const agg = aggregateRealism(defaultEngineConfig);
    const body = reportBody(agg);
    // 콘솔 출력(요약).
    // eslint-disable-next-line no-console
    console.log(`\n=== E3 REALISM GAP (${defaultEngineConfig.version}, ${agg.seeds} seeds) ===\n${body}\n`);
    // 데이터 표만 별도 파일로도 저장(md 본문에 붙여넣기용).
    const out = join(process.cwd(), "research", "engine-realism-gap.data.md");
    writeFileSync(
      out,
      `<!-- generated by gap-report.test.ts · ${defaultEngineConfig.version} · ${agg.seeds} seeds -->\n\n${body}\n`,
    );
    expect(agg.teamMatches).toBe(agg.seeds * 2);
  });
});
