/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/presets/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 팀 스냅샷 3슬롯 목록(빈 슬롯 포함) — 빈 슬롯은 name/snapshot/updatedAt=null */
        get: operations["listTeamPresets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/team/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프리셋 슬롯 번호(1|2|3) */
                slot: components["parameters"]["PresetSlot"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 스냅샷 저장(전체 교체). 검증 = 덱 검증 재사용(보유·선발 11·GK≥1·중복·프롬프트 길이,
         *     code=DECK_INVALID) + teamTactics 범위 0..1(code=VALIDATION_ERROR).
         */
        put: operations["saveTeamPreset"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/team/{slot}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프리셋 슬롯 번호(1|2|3) */
                slot: components["parameters"]["PresetSlot"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 스냅샷 → 현재 편집 상태(활성 덱 decks/deck_slots)로 반영. 덱 저장 재검증 수행(스냅샷 저장 후
         *     보유 풀이 바뀌었으면 DECK_INVALID). teamTactics는 덱에 컬럼이 없어 반영 대상 아님(스냅샷/매치
         *     스냅샷에만 존재하며 AI 컨텍스트로 전달).
         */
        post: operations["applyTeamPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 감독 관계 — 팀 사기(morale/streak) + 선수별 신뢰도(trust) & 성격(personality).
         *     브리핑/덱 화면 표시용(AC-C4). 관계 갱신은 매치 FINISHED 트랜잭션에서 서버가 처리(config 규칙).
         */
        get: operations["getRelations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conditions/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 오늘(KST)의 내 보유 선수 컨디션 — {playerId: 0.0~1.0}. 날짜 시드
         *     sha256(userId:yyyy-MM-dd:cond:playerId) 결정론 롤이라 KST 자정에만 갱신되고 매치와 무관하게
         *     하루 고정이다(덱/선수 리스트 상시 표시용). 매치 생성·킥오프 재캡처는 같은 값을
         *     matches.conditions_json 에 스냅샷하므로 엔진 입력·재현 계약은 불변.
         */
        get: operations["getTodayConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 트레이드 3슬롯 상태(WAITING 남은 시간·단축 비용, OPEN 오퍼 내용·확률) + 지갑 */
        get: operations["getTradeSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/{slot}/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * **[장 시작!]** — 슬롯의 장을 연다(능동 진입, #149). 새 시드로 오퍼를 확정하고
         *     `state=WAITING` + 레어도별 카운트다운(config) 시작, **등급만 공개**(targetGrade).
         *     IDLE 에서는 최초 시작, **OPEN 에서는 [거래 안함]**(공개된 선수를 버리고 새 오퍼·새 대기 —
         *     "장 시작을 다시 누른 것과 동일") 이며 이 경우 trade_log 에 DECLINED(detail.action=skip) 기록.
         *     WAITING/RESOLVING 에서는 400(TRADE_INVALID).
         */
        post: operations["startTradeSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/{slot}/speedup": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * WAITING 슬롯 대기 단축 — 남은시간 비례 포인트 차감(config), opens_at 앞당김. 원장
         *     ref=slotId+회차(멱등). 잔액 부족 시 402/400 INSUFFICIENT_POINTS.
         */
        post: operations["speedupTradeSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/{slot}/propose": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * FA 오퍼에 제안(내 보유 선수 + 포인트) → 가치비교 확률로 성공/실패(시드+제안해시 롤).
         *     실패해도 제안 자원 소실 없음(재제안 쿨타임 config). 성공 시 대상 선수 영입 반영.
         */
        post: operations["proposeTradeFa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/{slot}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TRADE 오퍼 수락(상대가 지목한 내 선수 ↔ 대가 선수) → 높은 확률(config, 예 0.8) 성공.
         *     성공 시 내 선수 이탈 + 대가 선수 영입. 결과는 trade_log 기록 + **슬롯 IDLE**(다음 장은
         *     [장 시작!] 로 유저가 연다, #149).
         */
        post: operations["acceptTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trade/{slot}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TRADE 오퍼 거절 → **슬롯 IDLE**(장 종료, #149 능동화). trade_log에 DECLINED 기록.
         *     새 오퍼를 바로 받으려면 `POST /{slot}/start`([거래 안함]) 를 쓴다.
         */
        post: operations["declineTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/league/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 시즌 시작 — ACTIVE 시즌 없으면 생성(봇 9팀 시드 구성 + 더블 라운드로빈 18R 일정 + 유저 18경기
         *     + 봇전 72경기). 직전 시즌이 FINISHED면 season_no+1로 새 시즌.
         */
        post: operations["startLeagueSeason"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/league": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 현재 시즌 상태·순위표(승점 3-1-0, 골득실→다득점→승자승)·일정·다음 유저 경기 */
        get: operations["getLeague"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/league/next-match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 다음 SCHEDULED 유저 픽스처로 매치 생성(mode=league, 상대=봇 로스터/성향, 홈/어웨이 반영) →
         *     이후 기존 매치 플로우. FINISHED 시 서버가 픽스처 정산 + 같은 라운드 봇전 간이결과 일괄 생성.
         */
        post: operations["startNextLeagueMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 경기 기록 리스트(모드·상대·스코어·리그 라운드). 필터=mode/season. */
        get: operations["listMatchLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 트레이드 이력(성공/실패/거절/만료 + 상세) */
        get: operations["listTradeLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유저 승수/승률 리더보드 상위 N + 내 순위 + 개인 기록(최다 득점 선수·연승 등) */
        get: operations["getRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 전 엔드포인트 공통 에러 코드(V1 열거 + Phase2 신규 TRADE_INVALID/LEAGUE_INVALID).
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "NOT_FOUND" | "DECK_INVALID" | "INSUFFICIENT_POINTS" | "INVALID_STATE" | "SUBSTITUTION_INVALID" | "AI_JOB_FAILED" | "TRADE_INVALID" | "LEAGUE_INVALID" | "INTERNAL_ERROR";
        ApiError: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        /** @enum {string} */
        Position: "GK" | "DF" | "MF" | "FW";
        /** @enum {string} */
        Grade: "BRONZE" | "SILVER" | "GOLD" | "DIA" | "LEGEND";
        /**
         * @description 선수 성격(P2-D7) — AI 컨텍스트 반응성에 영향. players.personality(data v2.1).
         * @enum {string}
         */
        Personality: "FIERY" | "CALM" | "GLASS" | "AMBITIOUS";
        /** @description 선수 요약 참조(트레이드/리그 표시용) */
        PlayerRef: {
            playerId: string;
            name: string;
            position: components["schemas"]["Position"];
            grade: components["schemas"]["Grade"];
        };
        Deck: {
            id: string;
            formation: string;
            slots: {
                playerId: string;
                /** @enum {string} */
                role: "starter" | "bench";
                slotIndex: number;
                promptText?: string | null;
            }[];
            /** Format: date-time */
            updatedAt?: string;
        };
        /**
         * @description 수동 팀 전술(P2-D4) — 각 0.0~1.0. zod manualTactics와 필드명 일치. AI는 이 값을 베이스(A)로
         *     받고 프롬프트로 보정만 한다(#82 A+B 구조 정합).
         */
        TeamTactics: {
            /** @description 수비 라인 높이 */
            line: number;
            /** @description 압박 강도 */
            press: number;
            /** @description 템포 */
            tempo: number;
            /** @description 폭 */
            width: number;
        };
        SnapshotSlot: {
            playerId: string;
            /** @description starter: 0..10(포메이션 슬롯), bench: 0.. */
            slotIndex: number;
            promptText?: string | null;
        };
        /** @description 스냅샷 본문 — team_presets.snapshot_json 정규화 형태(name은 슬롯 메타로 분리). */
        TeamSnapshot: {
            /** @description '4-4-2' 등 — 엔진 config 포메이션 키와 일치 */
            formation: string;
            starters: components["schemas"]["SnapshotSlot"][];
            bench: components["schemas"]["SnapshotSlot"][];
            teamTactics?: components["schemas"]["TeamTactics"];
            /** @description 팀 전체 사전 프롬프트 */
            teamPrompt?: string | null;
        };
        /** @description GET 응답 슬롯 항목. 빈 슬롯은 name/snapshot/updatedAt=null. */
        TeamPresetSlot: {
            /** @enum {integer} */
            slot: 1 | 2 | 3;
            name?: string | null;
            snapshot?: components["schemas"]["TeamSnapshot"] | null;
            /** Format: date-time */
            updatedAt?: string | null;
        };
        /** @description PUT 바디 — TeamSnapshot + 선택적 name(슬롯 이름). */
        TeamSnapshotSaveRequest: {
            /** @default 프리셋 */
            name: string;
            formation: string;
            starters: components["schemas"]["SnapshotSlot"][];
            bench: components["schemas"]["SnapshotSlot"][];
            teamTactics?: components["schemas"]["TeamTactics"];
            teamPrompt?: string | null;
        };
        /** @description {playerId: 0.0~1.0} 시드 결정론 컨디션 롤. 12시(1.0)=최고/6시(0.0)=최저 시계 UI. */
        ConditionMap: {
            [key: string]: number;
        };
        /**
         * @description V1 CreateMatchRequest {botId?} 에 teamTactics(선택) 추가. teamTactics는 매치 스냅샷
         *     (user_deck_json)에 포함돼 AI 컨텍스트로 전달된다.
         */
        CreateMatchRequestPhase2: {
            botId?: string | null;
            teamTactics?: components["schemas"]["TeamTactics"];
        };
        /** @description V1 MatchDetail에 **추가되는** Phase2 필드(기존 필드 불변). 웹은 병합 시 MatchDetail에 아래를 합친다. */
        MatchDetailPhase2Fields: {
            conditions?: components["schemas"]["ConditionMap"];
            /**
             * @default practice
             * @enum {string}
             */
            mode: "practice" | "league";
            /** @description 리그 경기면 league_fixtures 참조 */
            leagueFixtureId?: string | null;
            /**
             * @description 이 매치에 실제로 사용된 덱 스냅샷(matches.user_deck_json 을 읽어 노출만 — 새 저장 로직 없음).
             *     "과거 세팅 로그 → 프리셋으로 저장" 플로우 입력(#98 요구 2). 스냅샷이 없거나(구 매치) 형상이
             *     깨진 매치는 null.
             */
            userDeckSnapshot?: components["schemas"]["TeamSnapshot"] | null;
        };
        /** @description MatchDetail(V1) + Phase2 필드 — createMatch/next-match 응답 표현. */
        MatchDetailPhase2: {
            id?: string;
            /** @enum {string} */
            state?: "BRIEFING" | "GEN1" | "FIRST_HALF" | "HALFTIME" | "SECOND_HALF" | "GEN2" | "FINISHED" | "FAILED" | "H1_BREAK";
            /** Format: date-time */
            createdAt?: string;
        } & components["schemas"]["MatchDetailPhase2Fields"];
        PlayerRelation: {
            playerId: string;
            /** @description 신뢰도(기용/승패/교체로 변동, config 규칙) */
            trust: number;
            personality: components["schemas"]["Personality"];
        };
        RelationsResponse: {
            /** @description 팀 사기(연승/연패로 변동) */
            morale: number;
            /** @description +연승 / -연패 */
            streak: number;
            players: components["schemas"]["PlayerRelation"][];
        };
        /** @description V1 CatalogPlayer에 추가되는 personality 필드(도감/덱 표시용). */
        CatalogPlayerPhase2Fields: {
            personality?: components["schemas"]["Personality"];
        };
        /**
         * @description IDLE: 장이 닫힘(오퍼 없음) — 유저가 `POST /{slot}/start`("장 시작!")를 눌러야 오퍼가 생성된다.
         *     WAITING: 오퍼 확정 + 카운트다운(등급만 공개, 선수 정체는 비공개). OPEN: 거래 가능(전면 공개).
         *     RESOLVING: 판정 진행 중(과도 상태).
         * @enum {string}
         */
        TradeState: "IDLE" | "WAITING" | "OPEN" | "RESOLVING";
        /** @enum {string} */
        TradeOfferKind: "FA" | "TRADE";
        WalletInfo: {
            points: number;
        };
        /**
         * @description 슬롯 상태. IDLE: 오퍼 없음(모든 오퍼 필드 null) — [장 시작!] 대기.
         *     WAITING: targetGrade(등급만 공개) + remainingSec/speedupCost. **아직 한 번도 공개된 적 없는
         *     오퍼면 target/demand/targetValue 는 null**(선수 정체는 카운트다운 만료 전까지 비공개).
         *     단 **이미 OPEN 으로 공개됐던 오퍼가 다시 WAITING 이 된 경우(FA 제안 실패 후 재제안 쿨타임)는
         *     계속 공개 상태를 유지**한다 — 유저가 이미 본 선수를 도로 가리지 않는다(인지 부조화 방지).
         *     클라이언트 분기 기준 = `target == null`(가려짐) vs `target != null`(공개된 채 쿨타임 대기).
         *     OPEN-FA: target(등장 선수) + 제안 확률 파라미터.
         *     OPEN-TRADE: target(대가 선수) + demand(상대가 지목한 내 선수) + acceptProbability.
         */
        TradeSlot: {
            /** @enum {integer} */
            slot: 1 | 2 | 3;
            state: components["schemas"]["TradeState"];
            offerKind?: components["schemas"]["TradeOfferKind"] | null;
            /** @description FA=등장 선수 / TRADE=대가 선수 */
            target?: components["schemas"]["PlayerRef"] | null;
            /** @description TRADE=상대가 지목한 내 선수 */
            demand?: components["schemas"]["PlayerRef"] | null;
            /**
             * Format: date-time
             * @description 카운트다운 만료 시각. IDLE(오퍼 없음)이면 null.
             */
            opensAt?: string | null;
            /** @description WAITING 남은 대기 초(0이면 곧 OPEN) */
            remainingSec?: number;
            /** @description 지금 단축 시 포인트 비용(잔여시간 비례, config) */
            speedupCost?: number | null;
            /** @description 대상 선수 가치(제안 확률 계산 근거, 표시용) */
            targetValue?: number | null;
            /** @description TRADE 수락 성공 확률(config, 서버 계산값) */
            acceptProbability?: number | null;
            /**
             * @description 대상 선수 등급(BRONZE|SILVER|GOLD|DIA|LEGEND). **WAITING 부터 공개** — 카운트다운
             *     중에는 등급만 알고 선수 정체는 모른다. IDLE 이면 null.
             */
            targetGrade?: string | null;
        };
        /** @description [장 시작!] / [거래 안함] 결과 — 새 오퍼 생성 후 WAITING 슬롯 */
        TradeStartResponse: {
            slot: components["schemas"]["TradeSlot"];
            wallet: components["schemas"]["WalletInfo"];
        };
        TradeSlotsResponse: {
            slots: components["schemas"]["TradeSlot"][];
            wallet: components["schemas"]["WalletInfo"];
        };
        TradeSpeedupResponse: {
            slot: components["schemas"]["TradeSlot"];
            wallet: components["schemas"]["WalletInfo"];
            /** @description 차감된 포인트 */
            spent: number;
        };
        FaProposeRequest: {
            /** @description 제안에 포함할 내 보유 선수 id들 */
            playerIds: string[];
            /** @description 함께 제안할 포인트 */
            points: number;
        };
        /** @enum {string} */
        TradeResult: "SUCCESS" | "FAIL" | "DECLINED" | "EXPIRED";
        /** @description propose/accept/decline 판정 결과. 성공 시 보유 풀 변동 포함. */
        TradeResolveResponse: {
            result: components["schemas"]["TradeResult"];
            probability?: number | null;
            /** @description 시드+제안해시 롤(감사/표시용) */
            roll?: number | null;
            /** @description 영입된 선수(성공 시) */
            acquired?: components["schemas"]["PlayerRef"] | null;
            /** @description 이탈한 내 선수(TRADE 성공 시) */
            released?: components["schemas"]["PlayerRef"] | null;
            wallet?: components["schemas"]["WalletInfo"];
            /** @description 판정 후 재생성된 슬롯 */
            slot: components["schemas"]["TradeSlot"];
        };
        TradeLogItem: {
            id: number;
            kind: components["schemas"]["TradeOfferKind"];
            result: components["schemas"]["TradeResult"];
            /** @description {target, offered:[...], points, probability, roll} — trade_log.detail_json */
            detail?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        LeagueTeam: {
            teamId: string;
            name: string;
            /** @description 봇 팀 성향(공격/수비/압박/역습…) */
            persona?: string | null;
            /** @description 팀 파워(봇전 간이결과 확률 모델 입력) */
            power?: number | null;
            isUser: boolean;
        };
        /** @description 순위표 행 — league_fixtures 파생(승점 3-1-0, 골득실→다득점→승자승). */
        LeagueStanding: {
            teamId: string;
            name: string;
            played: number;
            won: number;
            drawn: number;
            lost: number;
            goalsFor: number;
            goalsAgainst: number;
            goalDiff: number;
            points: number;
            rank: number;
            isUser: boolean;
        };
        LeagueFixture: {
            id: string;
            round: number;
            /** @description teamId */
            homeTeam: string;
            /** @description teamId */
            awayTeam: string;
            isUser: boolean;
            /** @enum {string} */
            state: "SCHEDULED" | "PLAYED";
            scoreHome?: number | null;
            scoreAway?: number | null;
            /** @description 유저 경기만(풀 시뮬 매치 참조) */
            matchId?: string | null;
        };
        LeagueSeason: {
            id: string;
            seasonNo: number;
            /** @enum {string} */
            state: "ACTIVE" | "FINISHED";
            teams: components["schemas"]["LeagueTeam"][];
            standings: components["schemas"]["LeagueStanding"][];
            fixtures: components["schemas"]["LeagueFixture"][];
            /** @description 다음 SCHEDULED 유저 경기(없으면 시즌 종료 임박) */
            nextUserFixture?: components["schemas"]["LeagueFixture"] | null;
            /** @description 시즌 보상 요약(additive, 시즌종료 연출용 — P3-D8/AC-E1). SoT=point_ledger 지급행 + 순위 파생. */
            seasonReward?: components["schemas"]["SeasonReward"];
        };
        /** @description 시즌 보상 요약. status 로만 지급 여부를 구분한다(PENDING 에서 points 는 예정액이 아니라 0). */
        SeasonReward: {
            /** @description 유저 최종 순위(진행 중이면 현재 잠정 순위, 미확인 방어 케이스는 -1) */
            rank: number;
            /** @description 실지급 포인트(원장 delta). PENDING/NONE 이면 0 */
            points: number;
            /**
             * @description PENDING=시즌 진행 중(미지급) / GRANTED=지급됨 / NONE=종료됐으나 보상 없음(방어)
             * @enum {string}
             */
            status: "PENDING" | "GRANTED" | "NONE";
            /** @description 지급 시각(원장 created_at). 미지급이면 null */
            awardedAt?: string | null;
        };
        LeagueResponse: {
            /** @description ACTIVE 시즌 없으면 null(시작 CTA) */
            season?: components["schemas"]["LeagueSeason"] | null;
        };
        LeagueNextMatchResponse: {
            match: components["schemas"]["MatchDetailPhase2"];
            fixture: components["schemas"]["LeagueFixture"];
        };
        MatchLogItem: {
            /** @description matchId — 상세 하프 로그 재생 링크에 사용 */
            id: string;
            /** @enum {string} */
            mode: "practice" | "league";
            opponentName: string;
            /** @description 픽스처(=엔진) 관점 홈 득점. 유저 관점은 userWasHome 로 오리엔트. */
            scoreHome?: number | null;
            /** @description 픽스처(=엔진) 관점 어웨이 득점. 유저 관점은 userWasHome 로 오리엔트. */
            scoreAway?: number | null;
            /**
             * @description 유저 관점 결과(어웨이 리그경기면 flip 반영).
             * @enum {string|null}
             */
            result: "WIN" | "DRAW" | "LOSS" | null;
            /** @description 리그 경기면 시즌 번호 */
            seasonNo?: number | null;
            /** @description 리그 경기면 라운드 */
            round?: number | null;
            /** @description additive(W4). 유저가 이 경기에서 홈 사이드였는지. scoreHome/scoreAway 가 픽스처 관점이라 유저 득점=userWasHome?scoreHome:scoreAway 로 오리엔트한다. 연습·유저홈 리그경기는 true. */
            userWasHome?: boolean;
            /** @description additive(W4). 하프 로그(match_halves)가 존재해 상세 재생이 가능한지. */
            hasHalves?: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        RankingEntry: {
            userId: string;
            nickname: string;
            wins: number;
            winRate: number;
            rank: number;
        };
        /** @description 개인 기록(매치 이벤트 파생) — 최다 득점 선수·최다 연승 등. */
        PersonalRecords: {
            topScorer?: components["schemas"]["PlayerRef"] | null;
            topScorerGoals?: number | null;
            longestWinStreak?: number;
            totalMatches?: number;
        };
        RankingsResponse: {
            leaderboard: components["schemas"]["RankingEntry"][];
            me: components["schemas"]["RankingEntry"];
            personalRecords: components["schemas"]["PersonalRecords"];
        };
        /** @description 마킹 지시 해석용(상대 이름→playerId 매핑 근거) */
        OpponentRosterEntry: {
            playerId: string;
            name: string;
            position: components["schemas"]["Position"];
        };
        /** @description 선수별 관계 컨텍스트 {playerId: {trust, personality}} */
        RelationContext: {
            [key: string]: {
                trust: number;
                personality: components["schemas"]["Personality"];
            };
        };
        /**
         * @description V1 AiJobContext(=shared TeamInputJobContext)에 **추가되는** additive optional 필드
         *     (LLD-p2-server §4 / LLD-p2-servants §2). zod `.optional()`이라 구계약 호환 — 출력 스키마
         *     (TacticalInput)는 불변(P2-D8). p2-servants가 shared zod를 동기 확장(매니저 조율).
         */
        AiJobContextPhase2Fields: {
            manualTactics?: components["schemas"]["TeamTactics"];
            conditions?: components["schemas"]["ConditionMap"];
            relations?: components["schemas"]["RelationContext"];
            teamMorale?: {
                morale: number;
                streak: number;
            };
            opponentRoster?: components["schemas"]["OpponentRosterEntry"][];
        };
        /**
         * @description B(패치 생성) 잡 컨텍스트의 **추가 필드**(additive) — kind 를 `team-input-patch` 로 두고
         *     A(베이스 생성) 결과 TacticalInput 을 `base` 로 싣는다. 나머지 필드는 V1 AiJobContext
         *     (=shared `TeamInputJobContext`) + `AiJobContextPhase2Fields` 를 **그대로 재사용**한다
         *     (shared `TeamInputPatchJobContext` = TeamInputJobContext.omit(kind).extend({kind, base})).
         *     상세·검증은 `packages/shared/src/team-input-job.ts`·`tactical-patch.ts`(zod)가 SoT —
         *     여기서는 느슨히 계약한다. 실행기는 이 컨텍스트로 `TacticalPatch` 를 생성→`applyPatch(base, patch,
         *     {seed})`→**완전한 TacticalInput** 을 반환한다(Java 는 team-input 과 동일하게 TacticalInput 소비).
         */
        AiJobContextPatchFields: {
            /**
             * @description V1 은 `team-input` 만. A+B 분리에서 `team-input-patch` 추가(B 잡). 크로스매치 캐시된 A 결과
             *     위에 패치를 정적 머지 → 출력 토큰 억제(perf #82: 6805→~1193). seed 는 통과 필드로 머지 시
             *     halfSeed 주입(A/B 콘텐츠의 seed 는 무시).
             * @enum {string}
             */
            kind?: "team-input" | "team-input-patch";
            /**
             * @description A(베이스 생성) 결과 TacticalInput. 이 위에 B 의 TacticalPatch 를 정적 머지한다.
             *     `team-input-patch` 잡에만 존재. 형태는 V1 AiJobResult(=shared TacticalInput) zod 가 SoT라
             *     여기서는 느슨히(오브젝트) 계약한다.
             */
            base?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description B(패치 생성) 잡의 출력 — A(베이스) TacticalInput 에 **정적 머지**하면 완전한 TacticalInput 이 된다
         *     (`applyPatch`). "전원 압박"·"수비진 라인 올려" 류 벌크 지시를 몇 줄로 표현해 출력 토큰을 억제.
         *     모든 필드 additive optional, 값은 **절대값**(상대 증분 아님). 적용 순서 team → byPosition →
         *     byPlayer → markTargets. **SoT = shared `packages/shared/src/tactical-patch.ts`(zod, 전계층 strict)** —
         *     여기서는 느슨히(형태만) 계약한다. 최종 zod 검증 + 클램프는 **머지 산출물**에 적용(B 출력 자체 아님).
         */
        TacticalPatch: {
            /** @description 팀 전술 평탄 패치(pressIntensity/pressTriggerLine 는 pressingScheme 로 되돌림). */
            team?: {
                defensiveLineHeight?: number;
                compactness?: number;
                tempo?: number;
                width?: number;
                pressIntensity?: number;
                pressTriggerLine?: number;
                offsideTrap?: boolean;
            };
            /** @description 포지션 그룹(GK/DF/MF/FW) 벌크 조정 — 그룹 전원에 적용. */
            byPosition?: {
                GK?: components["schemas"]["PositionPatch"];
                DF?: components["schemas"]["PositionPatch"];
                MF?: components["schemas"]["PositionPatch"];
                FW?: components["schemas"]["PositionPatch"];
            };
            /** @description {playerId: 개별 패치}. */
            byPlayer?: {
                [key: string]: {
                    /** @description PlayerBehavior 부분 패치(9필드 0..1, shared zod SoT). */
                    behavior?: {
                        [key: string]: unknown;
                    };
                    basePosition?: {
                        x?: number;
                        y?: number;
                    };
                    mentalModifier?: number;
                    duty?: string;
                };
            };
            /** @description 전담 마크 {수비수 playerId: 상대 targetId} — 마지막에 적용. */
            markTargets?: {
                [key: string]: string;
            };
        };
        /** @description 포지션 그룹 벌크 패치 값(그룹 전원 적용). */
        PositionPatch: {
            /** @description PlayerBehavior 부분 패치(shared zod SoT). */
            behavior?: {
                [key: string]: unknown;
            };
            mentalModifier?: number;
        };
    };
    responses: {
        /** @description 인증 실패(토큰 없음/만료/무효). code=UNAUTHORIZED */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 리소스 없음. code=NOT_FOUND */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        /** @description 프리셋 슬롯 번호(1|2|3) */
        PresetSlot: 1 | 2 | 3;
        /** @description 트레이드 슬롯 번호(1|2|3) */
        TradeSlotNo: 1 | 2 | 3;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTeamPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 항상 3개(slot 1..3) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPresetSlot"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveTeamPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프리셋 슬롯 번호(1|2|3) */
                slot: components["parameters"]["PresetSlot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamSnapshotSaveRequest"];
            };
        };
        responses: {
            /** @description 저장된 슬롯 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPresetSlot"];
                };
            };
            /** @description 스냅샷 검증 실패. code=DECK_INVALID(덱 규칙) 또는 VALIDATION_ERROR(teamTactics/slot) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    applyTeamPreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 프리셋 슬롯 번호(1|2|3) */
                slot: components["parameters"]["PresetSlot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 반영된 활성 덱(V1 Deck 스키마) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description 스냅샷을 덱으로 반영할 때 검증 실패. code=DECK_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 비어 있는 슬롯. code=NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getRelations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTodayConditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 보유 선수만(미보유 제외). 보유 0이면 빈 객체. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionMap"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getTradeSlots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeSlotsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startTradeSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 새 오퍼로 WAITING 진입한 슬롯 + 지갑 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeStartResponse"];
                };
            };
            /** @description 슬롯이 IDLE·OPEN 이 아님(카운트다운 중 재시작 불가). code=TRADE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    speedupTradeSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 단축됨(갱신된 슬롯 + 지갑 + 차감 포인트) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeSpeedupResponse"];
                };
            };
            /** @description 슬롯 상태가 WAITING이 아님 등. code=TRADE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 잔액 부족. code=INSUFFICIENT_POINTS */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    proposeTradeFa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FaProposeRequest"];
            };
        };
        responses: {
            /** @description 판정 결과(성공/실패) + 갱신 지갑/보유 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResolveResponse"];
                };
            };
            /** @description 슬롯이 OPEN-FA가 아님·미보유 선수 제안·쿨타임 등. code=TRADE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptTrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 판정 결과 + 갱신 보유 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResolveResponse"];
                };
            };
            /** @description 슬롯이 OPEN-TRADE가 아님. code=TRADE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    declineTrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 트레이드 슬롯 번호(1|2|3) */
                slot: components["parameters"]["TradeSlotNo"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 거절됨(IDLE 슬롯) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeResolveResponse"];
                };
            };
            /** @description 슬롯이 OPEN-TRADE가 아님. code=TRADE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    startLeagueSeason: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 생성/조회된 ACTIVE 시즌 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            /** @description 이미 ACTIVE 시즌 진행 중 등. code=LEAGUE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK. 시즌이 없으면 season=null */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startNextLeagueMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 매치 생성됨(리그 뱃지·라운드 포함) — MatchDetail + Phase2 필드 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueNextMatchResponse"];
                };
            };
            /** @description ACTIVE 시즌 없음·남은 유저 픽스처 없음(시즌 종료). code=LEAGUE_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMatchLogs: {
        parameters: {
            query?: {
                mode?: "practice" | "league";
                season?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchLogItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTradeLogs: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeLogItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRankings: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
