/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 닉네임 로그인(목업, D8) — 신규면 유저+지갑 생성 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 자체 로그인 회원가입(P3-D2, additive) — id(=nickname)+비번. 성공 시 로그인과 동일한
         *     세션 토큰을 즉시 발급하고 신규 유저 온보딩(지갑+스타터 팩+원장)을 태운다.
         *     ⚠️ 비번 평문 저장은 내부 테스터 배포용 임시 목업 — 해시 전환은 백로그.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 정보(유저+지갑+전적) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 전적 리스트(최근 20) */
        get: operations["listMyMatches"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 카탈로그 전체(110명) + 보유 플래그(도감/덱 화면 공용) */
        get: operations["listPlayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 활성 덱 + 슬롯 + 선수별 프롬프트 */
        get: operations["getDeck"];
        /** 덱 전체 교체(부분수정 없음) — AC-S2 */
        put: operations["updateDeck"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 프리셋 목록 */
        get: operations["listPresets"];
        put?: never;
        /** 프리셋 생성 */
        post: operations["createPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 프리셋 삭제(수정=삭제+생성으로 단순화, LLD §4). 이미 덱에 복사 저장된 prompt_text는
         *     유지된다(AC-S4).
         */
        delete: operations["deletePreset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shop/gacha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 뽑기(단뽑/10연뽑) — LLD §4.1 */
        post: operations["gacha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게임 모드 목록(싱글 available, 멀티 "준비중" — D10) */
        get: operations["listModes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 매치 생성(BRIEFING 진입) — 봇 매칭 + 활성 덱 스냅샷 + 시드 생성 */
        post: operations["createMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /**
         * 매치 상태 조회(폴링용). BRIEFING이면 opponent(상대 분석) 포함. state별로 노출 필드가
         *     다르다 — 상세는 MatchDetail 스키마 설명 참고(§5.1).
         */
        get: operations["getMatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 팀/선수 프롬프트 입력(phase=pre|halftime) — 같은 대상 재입력은 UPSERT
         * @description 허용 상태(그 외 409 INVALID_STATE): phase=`pre` → BRIEFING /
         *     phase=`halftime` → **FIRST_HALF 또는 HALFTIME**(P4-E2 #170 — 전반을 보면서 후반 지시를
         *     미리 써두고, 감독시간에 마저 고칠 수 있다).
         */
        post: operations["submitMatchPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/kickoff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 킥오프 — 양팀 half1 AI 잡 enqueue, BRIEFING → GEN1 */
        post: operations["kickoffMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/halves/{half}/log": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
                half: 1 | 2;
            };
            cookie?: never;
        };
        /**
         * half별 MatchLog(재생용) — AC-M3, zod MatchLog 스키마와 계약
         * @description 허용 상태(그 외 409): half=1 → FIRST_HALF·HALFTIME·GEN2·SECOND_HALF·FINISHED /
         *     half=2 → **SECOND_HALF·FINISHED**.
         *
         *     로그는 해당 하프 **전체**를 내려준다. 라이브 재생 중 "앞서가기 금지"는 `MatchDetail.clock`
         *     기반 **클라 강제**다(P4-E2 R3 — 서버 절단은 PvP 백로그, 루트 §7 PvP-ready 경계와 정합).
         */
        get: operations["getHalfLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/halftime": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 하프타임 교체 저장(≤3, 벤치→선발만, resume 시 반영) — §5.4, AC-M4
         * @description 허용 상태(그 외 409): **FIRST_HALF·HALFTIME**(P4-E2 #170 — 전반 중 미리 짜두고 감독시간에 확정).
         *     상태 전이는 없다(후반 시뮬에서 반영).
         */
        post: operations["submitHalftimeSubs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 후반 시작 — half2 AI 잡 enqueue(전반 요약 컨텍스트 포함), HALFTIME → GEN2
         * @description 허용 상태 = **HALFTIME 만**. FIRST_HALF 에서 호출하면 409 — 후반 앞당기기는 금지다(P4-D1).
         *
         *     감독시간(`clock.phaseEndsAt`)이 만료되면 **서버가 같은 전이를 자동 수행**한다
         *     (`hmb.match.clock.auto-resume-on-expiry`). 이때 하프타임 프롬프트가 없으면 **전반 인풋이
         *     그대로 승계**된다(AI 콜 0 — AC-W2-2).
         */
        post: operations["resumeMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        /** 최종 결과(스코어·팀/선수 스탯·리포트). FINISHED에서만 의미 있음(읽기 전용) — §5.5 */
        get: operations["getMatchResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/matches/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** FAILED 매치의 실패 지점 재큐잉 — AC-M7 */
        post: operations["retryMatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ai-jobs/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI 잡 long-poll lease — LLD §6 */
        post: operations["pollAiJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/ai-jobs/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description promptHash(잡 ID) */
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 잡 완료 보고(성공/실패) — 성공 시 MatchOrchestrator.onJobDone 트리거 */
        post: operations["completeAiJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 큐 깊이·lease 중 개수(운영 확인용) — /internal/** 전체가 X-Servant-Token 보호(W4, AC-Q3) */
        get: operations["internalHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유저 목록·닉네임 검색·페이징(운영). 비밀번호는 어떤 필드로도 반환되지 않는다. */
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 유저 상태(지갑·보유 선수·활성 덱/프리셋 요약·전적) */
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{id}/points": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 포인트 지급(delta>0)/차감(delta<0) — AC-C1. 지갑·point_ledger(reason='admin_grant')·
         *     admin_audit 세 곳이 **하나의 트랜잭션**으로 갱신된다. 음수 잔액은 허용되지 않는다.
         */
        post: operations["adminGrantPoints"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 전 엔드포인트 공통 에러 코드 열거(LLD §3). 신규 코드 추가 시 이 열거에 먼저 반영한다
         *     (openapi.yaml이 계약 SoT).
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "UNAUTHORIZED" | "NOT_FOUND" | "DECK_INVALID" | "INSUFFICIENT_POINTS" | "INVALID_STATE" | "SUBSTITUTION_INVALID" | "AI_JOB_FAILED" | "INTERNAL_ERROR" | "BAD_CREDENTIALS" | "DUPLICATE_NICKNAME" | "FORBIDDEN" | "CONFLICT";
        /**
         * @example {
         *       "code": "DECK_INVALID",
         *       "message": "선발이 11명이 아닙니다",
         *       "detail": {
         *         "starterCount": 10
         *       }
         *     }
         */
        ApiError: {
            code: components["schemas"]["ErrorCode"];
            /** @description 사람이 읽을 수 있는 사유(한국어 가능) */
            message: string;
            detail?: {
                [key: string]: unknown;
            } | null;
        };
        LoginRequest: {
            /**
             * @description Phase2 additive — 생략 시 guest (server 9c51446 구현 정합).
             *     P3 additive: local = 자체 로그인(비번 필요, P3-D2).
             * @enum {string}
             */
            provider?: "guest" | "mock:google" | "mock:apple" | "local";
            /** @description provider=local 에서는 이 닉네임이 곧 로그인 id 다(별도 식별자 없음) */
            nickname: string;
            /**
             * @description P3 additive(옵션) — provider=local 일 때만 사용한다. 다른 provider 는 무시.
             *     ⚠️ 평문 저장 목업(P3-D2, 해시 전환 백로그). 응답·로그 어디에도 반환되지 않는다(AC-A2).
             */
            password?: string;
        };
        /** @description 자체 로그인 회원가입 바디(P3 §A). nickname = 로그인 id(users.nickname UNIQUE 재사용). */
        RegisterRequest: {
            nickname: string;
            /** @description 길이 규칙은 서버 config(hmb.auth.local.password-*-length). 평문 목업(P3-D2). */
            password: string;
        };
        UserRef: {
            /** @description ULID */
            id: string;
            nickname: string;
            /**
             * @description P3 §C additive(선택 필드 — required 불변). GET /api/me 응답에만 담긴다.
             *     web 이 /admin 라우트를 **표시**할지 정하는 힌트일 뿐 권한 판정이 아니다 —
             *     실제 접근 차단은 서버의 /api/admin/** 게이트가 한다.
             */
            isAdmin?: boolean;
        };
        LoginResponse: {
            /** @description 불투명 세션 토큰(Bearer로 사용) */
            token: string;
            user: components["schemas"]["UserRef"];
            /** @description 신규 가입이면 true(스타터 팩 지급 트리거, PRD §3.2) */
            isNew: boolean;
        };
        WalletInfo: {
            points: number;
        };
        MatchRecordSummary: {
            wins: number;
            draws: number;
            losses: number;
        };
        MeResponse: {
            user: components["schemas"]["UserRef"];
            wallet: components["schemas"]["WalletInfo"];
            records: components["schemas"]["MatchRecordSummary"];
        };
        MatchListItem: {
            /** @description P2 additive — 유저 관점 오리엔트 키(연습=true, 리그 어웨이=false). scoreHome/Away는 픽스처 관점 유지 */
            userWasHome?: boolean;
            id: string;
            opponentName: string;
            scoreHome: number | null;
            scoreAway: number | null;
            /** @enum {string|null} */
            result: "WIN" | "DRAW" | "LOSS" | null;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description shared PlayerAttributes(packages/shared/src/select-data.ts) — 각 0..100 */
        PlayerAttributes: {
            technical: number;
            mental: number;
            physical: number;
            passing: number;
            shooting: number;
            tackling: number;
            pace: number;
            stamina: number;
            positioning: number;
        };
        /** @enum {string} */
        Grade: "BRONZE" | "SILVER" | "GOLD" | "DIA" | "LEGEND";
        /** @enum {string} */
        Position: "GK" | "DF" | "MF" | "FW";
        CatalogPlayer: {
            /** @description 'P001'.. 고유 ID(실선수 아님, data 에픽 시드) */
            id: string;
            name: string;
            position: components["schemas"]["Position"];
            grade: components["schemas"]["Grade"];
            attributes: components["schemas"]["PlayerAttributes"];
            owned: boolean;
            ownedCount: number;
        };
        DeckSlot: {
            playerId: string;
            /** @enum {string} */
            role: "starter" | "bench";
            /** @description starter: 0..10(포메이션 슬롯), bench: 0..6 */
            slotIndex: number;
            /** @description 선수별 사전 프롬프트(≤500자, hmb.deck.player-prompt-max-chars) */
            promptText?: string | null;
        };
        Deck: {
            id: string;
            /** @description '4-4-2' 등 — 엔진 config 포메이션 키와 일치해야 함 */
            formation: string;
            slots: components["schemas"]["DeckSlot"][];
            /** Format: date-time */
            updatedAt?: string;
        };
        DeckUpdateRequest: {
            formation: string;
            /**
             * @description starter 슬롯 정확히 11개(slotIndex 0..10, GK≥1 포함), bench ≤7(hmb.deck.bench-max),
             *     선수 중복 금지, 미보유 선수 금지 — 위반 시 400 DECK_INVALID(AC-S2).
             */
            slots: components["schemas"]["DeckSlot"][];
        };
        PromptPreset: {
            id: string;
            name: string;
            promptText: string;
            /** Format: date-time */
            createdAt: string;
        };
        PromptPresetCreateRequest: {
            name: string;
            promptText: string;
        };
        GachaRequest: {
            /** @enum {string} */
            kind: "single" | "ten";
        };
        GachaResultItem: {
            player: components["schemas"]["CatalogPlayer"];
            /** @description PoC 정책 — 중복은 보유 수량 증가, 능력엔 영향 없음(표시만) */
            isNew: boolean;
        };
        GachaResponse: {
            /** @description single=1개, ten=11개(골드↑ ≥1, pity 적용 가능 — AC-S7) */
            results: components["schemas"]["GachaResultItem"][];
            wallet: components["schemas"]["WalletInfo"];
        };
        ModeInfo: {
            /** @enum {string} */
            id: "single" | "multi";
            available: boolean;
            /** @description available=false일 때 표시 문구(예: '준비중', D10) */
            label?: string | null;
        };
        /**
         * @description LLD §5.1 상태머신 + **P4-E2(#170) 확장** — docs/plan-v5/LLD-e2-flow-clock.md §2.
         *
         *     BRIEFING → GEN1 → **FIRST_HALF**(전반 라이브 재생 창) → **HALFTIME**(감독시간 60초)
         *     → GEN2 → **SECOND_HALF** → FINISHED. 라이브 단계 전이는 **서버 시계가 소유**한다
         *     (화면을 안 봐도 진행 — P4-D1/D2).
         *
         *     `H1_BREAK` 은 **레거시 전용**(P4 이전 배포본의 진행 중 매치를 V8 마이그레이션이 HALFTIME 으로
         *     옮긴다). 신규 매치는 이 값이 되지 않는다.
         * @enum {string}
         */
        MatchState: "BRIEFING" | "GEN1" | "FIRST_HALF" | "HALFTIME" | "SECOND_HALF" | "GEN2" | "FINISHED" | "FAILED" | "H1_BREAK";
        /**
         * @description **서버 권위 시계**(P4-D1, #170). 서버는 "지금 어느 단계이고 그 단계가 언제 시작해 언제
         *     끝나는가"(=창)만 소유하고, 재생 위치(틱)는 클라가 그 창 안에서 계산한다
         *     (`packages/shared/src/match-clock.ts` 가 매핑의 단일 SoT).
         *
         *     `MatchDetail.clock = null` 인 경우: 라이브 단계가 아님(BRIEFING/GEN*\/FINISHED/FAILED),
         *     또는 `hmb.match.clock.enabled=false`(롤백), 또는 레거시 매치.
         */
        MatchClock: {
            /**
             * @description 현재 단계(state 파생 — SoT 는 state).
             * @enum {string}
             */
            phase: "FIRST_HALF" | "HALFTIME" | "SECOND_HALF";
            /**
             * Format: date-time
             * @description 전반이 라이브로 열린 시각(AC-W3-3). 전반 로그 저장 시점이며 킥오프 요청 시점이 아니다.
             */
            kickoffAt?: string | null;
            /**
             * Format: date-time
             * @description 현재 단계 시작. null = 시계 미적용(레거시·롤백).
             */
            phaseStartAt?: string | null;
            /**
             * Format: date-time
             * @description 현재 단계 종료 예정. HALFTIME 이면 **감독시간 deadline**.
             */
            phaseEndsAt?: string | null;
            /**
             * Format: date-time
             * @description 응답 생성 시각 — 클라 시계 스큐 보정 기준.
             */
            serverNow: string;
            /** @description 하프당 실시간 재생 길이(config `hmb.match.clock.half-real-ms`). 압축비는 이 값에서 파생. */
            halfRealMs: number;
            /** @description 감독시간 길이(config, P4-D2 = 60000). */
            halftimeMs: number;
            /** @description 라이브 앞서가기 금지(config). 뒤로 스크럽은 항상 자유. */
            seekForwardBlocked: boolean;
            /** @description 지연·스큐 허용 오차(config). */
            seekGraceMs: number;
        };
        OpponentAnalysisPlayer: {
            name: string;
            position: components["schemas"]["Position"];
            grade: components["schemas"]["Grade"];
            hasPrompt?: boolean;
        };
        OpponentAnalysis: {
            name: string;
            analysisText: string;
            deck: components["schemas"]["OpponentAnalysisPlayer"][];
        };
        /**
         * @description state에 따라 일부 필드만 채워진다: BRIEFING → opponent 포함. HALFTIME(구 H1_BREAK) 이후 →
         *     scoreH1Home/Away. FINISHED → scoreHome/Away+result. FAILED → failReason.
         *     라이브 단계(FIRST_HALF/HALFTIME/SECOND_HALF) → clock(P4-E2 #170).
         *     후반 스코어는 **FINISHED 전까지 노출하지 않는다**(재생 중 스포일러 금지).
         */
        MatchDetail: {
            id: string;
            state: components["schemas"]["MatchState"];
            failReason?: string | null;
            opponent?: components["schemas"]["OpponentAnalysis"];
            scoreH1Home?: number | null;
            scoreH1Away?: number | null;
            scoreHome?: number | null;
            scoreAway?: number | null;
            /** @enum {string|null} */
            result?: "WIN" | "DRAW" | "LOSS" | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            finishedAt?: string | null;
            /** @description 서버 권위 시계(P4-E2 #170, additive). 라이브 단계가 아니거나 시계 비활성이면 null. */
            clock?: components["schemas"]["MatchClock"] | null;
        };
        CreateMatchRequest: {
            /** @description 생략 시 랜덤 봇(BOT_ATK/BOT_DEF/BOT_BAL 중, PRD §3.4) */
            botId?: string | null;
        };
        MatchPromptRequest: {
            /** @enum {string} */
            phase: "pre" | "halftime";
            /** @enum {string} */
            scope: "team" | "player";
            /** @description scope='player'일 때 필수 */
            playerId?: string | null;
            text: string;
        };
        SubstitutionItem: {
            /** @description playerId(전반 선발) */
            out: string;
            /** @description playerId(벤치) */
            in: string;
        };
        HalftimeRequest: {
            /** @description ≤3(hmb.match.halftime-subs-max), out∈전반 선발, in∈벤치, 교체 후 GK≥1 */
            substitutions: components["schemas"]["SubstitutionItem"][];
        };
        MatchResult: {
            matchId: string;
            scoreHome: number;
            scoreAway: number;
            /** @enum {string} */
            result: "WIN" | "DRAW" | "LOSS";
            /** @description 승/무/패 보상(economy.v1.json 수치, 멱등 지급 — AC-M6) */
            pointsAwarded?: number;
            /** @description 팀 스탯 요약(슛/점유율 등) — 상세는 W3 구현에서 확정 */
            teamStats?: {
                [key: string]: unknown;
            };
            /** @description 선수별 스탯 리스트 — 상세는 W3 구현에서 확정 */
            playerStats?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * @description packages/shared/src/select-data.ts (zod SoT). home/away 각각 TeamRoster
         *     {name, players: PlayerCard[]}. PlayerCard = {playerId, name, position, attributes}.
         *     여기서는 필드 상세를 반복하지 않고 존재만 계약한다 — zod 스키마가 진실.
         */
        SelectData: {
            home: {
                [key: string]: unknown;
            };
            away: {
                [key: string]: unknown;
            };
        };
        /**
         * @description packages/shared/src/tactical-input.ts (zod SoT). AI가 프롬프트로부터 생성하는
         *     선수별 행동 파라미터 세트이자 결정론 엔진 입력. 필드: seed(string, uint64를 10진
         *     문자열로), team(TeamInput: formation·defensiveLineHeight·compactness·tempo·width·
         *     pressingScheme·offsideTrap), players(PlayerInput[]: playerId·role·duty·basePosition·
         *     behavior·markTarget?·mentalModifier), meta?(generatedAt?·promptHash?).
         */
        TacticalInput: {
            seed: string;
            team: {
                [key: string]: unknown;
            };
            players: {
                [key: string]: unknown;
            }[];
            meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description packages/shared/src/match-log.ts (zod SoT). 결정론 엔진 출력 — 틱별 좌표 스냅샷 +
         *     이벤트 시계열 + 최종 스코어 + 틱 해시(재현/desync 검증). 필드: configVersion, seed,
         *     tickSnapshots(TickSnapshot[]: tick·minute·ball·ballOwner·players·hash),
         *     events(MatchEvent[]: tick·minute·type·team?·playerId?·xg?·detail?), finalScore
         *     {home,away}. AC-M3: 이 응답은 zod MatchLog로 파싱 가능해야 한다.
         */
        MatchLog: {
            configVersion: string;
            seed: string;
            tickSnapshots: {
                [key: string]: unknown;
            }[];
            events: {
                [key: string]: unknown;
            }[];
            finalScore: {
                home?: number;
                away?: number;
            };
        };
        AiJobPollRequest: {
            workerId: string;
            /**
             * @description long-poll 최대 대기(ms). virtual thread라 블로킹 허용(LLD §6).
             * @default 25000
             */
            waitMs: number;
        };
        /**
         * @description AI 실행기 입력(LLD-ts-servants §3과 동일 계약, LLD-server-java §5.2). kind='team-input'
         *     고정. 필드: matchId, side(home|away), half(1|2), seed, formation, roster(11명
         *     {playerId,name,position,attributes,slotIndex}), teamPrompt, playerPrompts
         *     ({playerId: text}), prevSummary?(half2만: {scoreHome,scoreAway,shots,possessionHint}).
         */
        AiJobContext: {
            /** @enum {string} */
            kind: "team-input";
            matchId: string;
            /** @enum {string} */
            side: "home" | "away";
            /** @enum {integer} */
            half: 1 | 2;
            seed: string;
            formation: string;
            roster: {
                [key: string]: unknown;
            }[];
            teamPrompt: string;
            playerPrompts: {
                [key: string]: string;
            };
            prevSummary?: {
                [key: string]: unknown;
            } | null;
        };
        AiJobUsage: {
            inputTokens?: number;
            outputTokens?: number;
            cacheReadTokens?: number;
            cacheCreateTokens?: number;
            costUSD?: number;
        };
        AiJob: {
            /** @description promptHash(멱등 키, sha256 hex 16+) */
            id: string;
            matchId?: string | null;
            /** @enum {string|null} */
            side?: "home" | "away" | null;
            /** @enum {integer|null} */
            half?: 1 | 2 | null;
            /** @enum {string} */
            status: "queued" | "leased" | "done" | "failed";
            context: components["schemas"]["AiJobContext"];
            result?: components["schemas"]["TacticalInput"];
            error?: string | null;
            usage?: components["schemas"]["AiJobUsage"];
            attempts?: number;
            /** Format: date-time */
            leaseUntil?: string | null;
        };
        AiJobCompleteRequest: {
            ok: boolean;
            /** @description ok=true일 때 필수 */
            output?: components["schemas"]["TacticalInput"];
            /** @description ok=false일 때 필수(attempts<max면 queued 복귀, 아니면 failed — LLD §6) */
            error?: string | null;
            usage?: components["schemas"]["AiJobUsage"];
        };
        InternalHealth: {
            /** @description status='queued' 개수 */
            queueDepth: number;
            /** @description status='leased' 개수 */
            leasedCount: number;
        };
        /**
         * @description 운영 목록/상세의 유저 요약. **비밀번호 필드는 존재하지 않는다**(AC-A2 연장) —
         *     서버 조회 SQL 도 users.password 를 나열하지 않는다.
         */
        AdminUserRow: {
            id: string;
            nickname: string;
            /** @description guest / mock:google / mock:apple / local */
            authProvider: string;
            isAdmin: boolean;
            /**
             * Format: int64
             * @description 지갑 잔액
             */
            points: number;
            /** Format: date-time */
            createdAt: string;
        };
        AdminUserPage: {
            items: components["schemas"]["AdminUserRow"][];
            /**
             * Format: int64
             * @description 검색 조건에 맞는 전체 건수(페이지 크기 아님)
             */
            total: number;
            limit: number;
            offset: number;
        };
        AdminUserDetail: {
            user: components["schemas"]["AdminUserRow"];
            players: {
                /**
                 * Format: int64
                 * @description 보유 선수 종류 수
                 */
                distinct: number;
                /**
                 * Format: int64
                 * @description 중복 포함 총 보유 수
                 */
                total: number;
            };
            /** @description 활성 덱 요약(없으면 null) */
            deck?: {
                id: string;
                name: string;
                formation: string;
                starters: number;
                bench: number;
                /** Format: date-time */
                updatedAt: string;
            } | null;
            presets: {
                /** Format: int64 */
                promptPresets: number;
                /** Format: int64 */
                teamPresets: number;
            };
            records: components["schemas"]["MatchRecordSummary"];
        };
        AdminGrantPointsRequest: {
            /**
             * Format: int64
             * @description 0 이 아닌 정수. 양수=지급, 음수=차감(차감 후 잔액이 음수면 400).
             */
            delta: number;
            /** @description 운영 사유(감사 로그에 그대로 기록된다). 공백만이면 400. */
            reason: string;
        };
        AdminGrantPointsResult: {
            userId: string;
            /** Format: int64 */
            delta: number;
            /** @description false = 같은 멱등키의 재전송이라 아무것도 바뀌지 않았다. */
            applied: boolean;
            /**
             * Format: int64
             * @description 처리 후 지갑 잔액(재전송이면 현재 잔액).
             */
            balance: number;
            /** @description 실제 사용된 멱등키(헤더 미제공 시 서버가 채번한 값). */
            idempotencyKey: string;
            /** @description 기록된 admin_audit 행 ID(재전송이면 null). */
            auditId?: string | null;
        };
    };
    responses: {
        /** @description 인증 실패(토큰 없음/만료/무효). code=UNAUTHORIZED */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 리소스 없음. code=NOT_FOUND */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 입력 검증 실패. code=VALIDATION_ERROR */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 이미 사용 중인 닉네임(= 자체 로그인 id). code=DUPLICATE_NICKNAME. P3 §A(AC-A1). */
        DuplicateNickname: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 인증은 됐으나 권한이 없음(admin 전용 API 에 일반 유저 토큰). code=FORBIDDEN. P3 §C(AC-C2). */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 현재 매치 상태에서 허용되지 않는 액션(§5.1 전이표 외). code=INVALID_STATE. AC-M1. */
        InvalidState: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        MatchId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공(신규/기존 공통) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            /**
             * @description 자체 로그인(provider=local) 인증 실패 — 계정 미존재/비번 불일치/비번 없는 계정.
             *     code=BAD_CREDENTIALS(계정 존재 여부를 누설하지 않도록 사유를 구분하지 않는다). P3 §A.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description 가입 성공(isNew=true) — 응답에 비번은 절대 포함되지 않는다(AC-A2) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["ValidationError"];
            409: components["responses"]["DuplicateNickname"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyMatches: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchListItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPlayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogPlayer"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 아직 덱이 없음(신규 유저가 스타터 팩 지급 전 등) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    updateDeck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckUpdateRequest"];
            };
        };
        responses: {
            /** @description 저장된 덱(재조회와 동일) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /**
             * @description 검증 실패 — 보유하지 않은 선수/starter≠11/GK 0명(starter 중)/bench>7/중복 선수/
             *     프롬프트 길이 초과. code=DECK_INVALID
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listPresets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPreset"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPreset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptPresetCreateRequest"];
            };
        };
        responses: {
            /** @description 생성됨 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptPreset"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deletePreset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    gacha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GachaRequest"];
            };
        };
        responses: {
            /** @description 뽑기 결과 + 갱신된 지갑 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GachaResponse"];
                };
            };
            /** @description 잘못된 kind 등. code=VALIDATION_ERROR */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 잔액 부족(또는 400 — 서버 구현 선택, AC-S6). code=INSUFFICIENT_POINTS */
            402: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    listModes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeInfo"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createMatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateMatchRequest"];
            };
        };
        responses: {
            /** @description 생성됨(state=BRIEFING) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description 활성 덱이 유효하지 않음(AC-S2 규칙 재검증). code=DECK_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitMatchPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchPromptRequest"];
            };
        };
        responses: {
            /** @description 저장됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    kickoffMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 잡 큐잉됨(state=GEN1). 클라이언트는 GET /api/matches/{id} 폴링. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    getHalfLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
                half: 1 | 2;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchLog"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 매치/half 없음 또는 아직 시뮬 전(state 미도달) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            409: components["responses"]["InvalidState"];
        };
    };
    submitHalftimeSubs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HalftimeRequest"];
            };
        };
        responses: {
            /** @description 저장됨(상태 전이는 없음 — resume에서 반영) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            /** @description 교체 규칙 위반(3명 초과·벤치 외 선수·GK 퇴장 후 GK 0). code=SUBSTITUTION_INVALID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    resumeMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 잡 큐잉됨(state=GEN2) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    getMatchResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    retryMatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["MatchId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 재큐잉됨(실패 직전 GEN* 상태로 복귀) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    pollAiJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiJobPollRequest"];
            };
        };
        responses: {
            /** @description 잡 1개 lease됨(status=leased) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiJob"];
                };
            };
            /** @description waitMs까지 대기했지만 큐가 비어 있음 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    completeAiJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description promptHash(잡 ID) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiJobCompleteRequest"];
            };
        };
        responses: {
            /** @description 반영됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiJob"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["InvalidState"];
        };
    };
    internalHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalHealth"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    adminListUsers: {
        parameters: {
            query?: {
                /** @description 닉네임 부분 일치. LIKE 와일드카드(%, _)는 리터럴로 취급된다. */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    adminGrantPoints: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 선택. 주면 같은 키의 재전송은 **중복 지급되지 않는다**(원장 유니크 인덱스로 보장,
                 *     재전송 응답은 200 + applied=false). 주지 않으면 서버가 키를 채번하므로 재전송은
                 *     별개의 지급으로 처리된다 — 운영 UI 는 항상 이 헤더를 보낼 것.
                 */
                "Idempotency-Key"?: string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminGrantPointsRequest"];
            };
        };
        responses: {
            /** @description 적용됨(applied=true) 또는 멱등 재전송(applied=false, 상태 변화 없음) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminGrantPointsResult"];
                };
            };
            /**
             * @description delta 가 0/누락, reason 누락, 또는 차감 후 잔액이 음수가 되는 경우.
             *     code=VALIDATION_ERROR 또는 INSUFFICIENT_POINTS.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description 멱등키 충돌(같은 키가 이미 다른 지급에 쓰였다). code=CONFLICT.
             *     응답 본문에는 내부 SQL·스키마가 포함되지 않는다.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
}
